version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    command: redis-server --bind 0.0.0.0 --protected-mode no
    volumes:
      - redis_data:/data
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  service-one:
    build: ./service-one
    container_name: service-one
    ports:
      - "8082:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SERVER_PORT=8080
      - SPRING_REDIS_TIMEOUT=5000ms
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped

  service-two:
    build: ./service-two
    container_name: service-two
    ports:
      - "8083:8081"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SERVER_PORT=8081
      - SPRING_REDIS_TIMEOUT=5000ms
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  microservices-network:
    driver: bridge